version: '3.3'

volumes:
  static:
  media:
  pg_data:

services:

  db:
    container_name: foodgram-db
    image: postgres:15
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  frontend:
    container_name: foodgram-front
    image: tosky26/foodgram_frontend:latest
    volumes:
      - static:/app/result_build/

  backend:
    depends_on:
      - db
    container_name: foodgram_back
    image: tosky26/foodgram_backend:latest
    env_file: .env
    volumes: 
      - static:/app/static
      - media:/app/media

  nginx:
    depends_on:
      - backend
      - frontend
    container_name: foodgram-proxy
    image: tosky26/foodgram_nginx:latest
    ports:
      - "80:80"
    volumes:
      - static:/static
      - media:/media
      - ./docs/:/usr/share/nginx/html/api/docs/
