version: '3.3'

volumes:
  static:
  media:
  pg_data:

services:

  db:
    container_name: foodgram-db
    image: postgres:15
    env_file: .env
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data

  frontend:
    container_name: foodgram-front
    image: tosky26/foodgram_frontend:latest
    restart: always
    volumes:
      - static:/app/result_build/

  backend:
    depends_on:
      - db
    container_name: foodgram_back
    image: tosky26/foodgram_backend:latest
    env_file: .env
    restart: always
    ports:
      - "8000:8000"
    volumes: 
      - static:/app/static
      - media:/media

  nginx:
    depends_on:
      - backend
      - frontend
    container_name: foodgram-proxy
    image: tosky26/foodgram_gateway:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static:/static
      - media:/media
      - /usr/share/nginx/html/docs/:/usr/share/nginx/html/api/docs/:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
