RECIPE_NAME_LENGTH = 256
TAG_NAME_SLUG_LENGTH = 32
INGREDIENT_NAME_LENGTH = 128
INGREDIENT_MEASUREMENT_LENGTH = 64
MINIMUM_RECIPE_COOKING_TIME = 1
MINIMUM_INGREDIENT_AMOUNT = 1
MAX_EMAIL_LENGTH = 254
MAX_USENAMES_LENGTH = 150
USERNAME_REGEX = r'^[\w.@+-]+\Z'
FAST_TIME = 30
LONG_TIME = 60
TIME_RANGES = {
    'fast': (0, FAST_TIME - 1),
    'medium': (FAST_TIME, LONG_TIME),
    'long': (LONG_TIME + 1, 999),
}
